language: php

php: 7.1

before_script:
    - composer install

script:
    #- if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
    - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
    - docker run --rm -v $PWD:/app phpqa/security-checker security:check
    - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/EmailTest

deploy:
    provider: heroku
    api_key:
        secure: 30e80510-0973-4cb9-bce6-f28be0ce25f8
    app: continuous-deployment-esgi

notifications:
    email:
        recipients:
            - romain.richard.08@hotmail.fr
        on_success: never
        on_failure: always